services:
  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    container_name: ngircd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/config
    ports:
      - 6667:6667
    restart: unless-stopped

  ft_irc:
    image: ghcr.io/gawingowin/ft_irc:latest
    container_name: ft_irc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    ports:
      - ${FT_IRC_PORT}:${FT_IRC_PORT}
    command: ["${FT_IRC_PORT}", "${FT_IRC_PASSWORD}"]
    restart: unless-stopped
