services:
  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    container_name: ngircd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/config
    ports:
      - 6667:6667
    restart: unless-stopped

  ft_irc:
    image: ghcr.io/gawingowin/ft_irc:latest
    container_name: ft_irc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    ports:
      - ${FT_IRC_PORT}:${FT_IRC_PORT}
    command: ["${FT_IRC_PORT}", "${FT_IRC_PASSWORD}"]
    restart: unless-stopped

  load-generator:
    image: load-generator
    container_name: load-generator
    build:
      context: .
      dockerfile: e2e/Dockerfile
    restart: unless-stopped
    ports:
      - "${LOCUST_WEB_PORT}"
    environment:
      - LOCUST_WEB_PORT
      - LOCUST_USERS
      - LOCUST_HEADLESS
      - LOCUST_AUTOSTART
      - LOCUST_BROWSER_TRAFFIC_ENABLED=true
      - FT_IRC_HOST
      - FT_IRC_PORT
      - FT_IRC_PASSWORD
    depends_on:
      - ft_irc
