name: Docker image Build and Push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "ci/**", "103-e2e"]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/gawingowin/ft_irc

    steps:
    - uses: actions/checkout@v4
    - name: Set short SHA
      id: var
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PUSH_KEY }}
    - name: Build the Docker image
      run: |
        docker build --target release --file Dockerfile --tag $IMAGE_NAME:${{ steps.var.outputs.SHORT_SHA }} --tag $IMAGE_NAME:latest .
    - name: Push the Docker image
      run: |
        docker push $IMAGE_NAME:${{ steps.var.outputs.SHORT_SHA }}
        docker push $IMAGE_NAME:latest
