name: Docker CI image Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      CI_IMAGE_NAME: ghcr.io/gawingowin/ft_irc_ci

    steps:
    - uses: actions/checkout@v4
    - name: Set short SHA
      id: var
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PUSH_KEY }}
    - name: Build the Docker image
      run: |
        docker build --target ci --file Dockerfile --tag $CI_IMAGE_NAME:${{ steps.var.outputs.SHORT_SHA }} .
    - name: Push the Docker image
      run: docker push $CI_IMAGE_NAME:${{ steps.var.outputs.SHORT_SHA }}