name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "ci/**"]
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write  
    runs-on: ubuntu-latest
    container: ghcr.io/gawingowin/ft_irc_ci:27f5cf1
    steps:
    - uses: actions/checkout@v4
    - name: build test
      run: make -s build
    - name: run test
      run: make -s test
    - name: upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Test-Logs
        path: build/pkg/tests/Testing/Temporary/LastTest.log
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  format:
    permissions:
      contents: read
      pull-requests: write  
    runs-on: ubuntu-latest
    container: ghcr.io/gawingowin/ft_irc_ci:27f5cf1
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt install clang-format
      - name: show setteings
        run: |
          clang-format --version
          clang-format -dump-config
      - name: Run clang-format
        run: |
          git ls-files | grep -E "\.(c|cpp|h|hpp|tpp)$" | xargs clang-format -i -style=file || true
      - name: Check for changes
        run: |
          if ! git diff --quiet ; then
            git diff > unformatted.patch
            exit 1
          fi
      - name: upload unformatted files
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Formatted-Files
          path: ./unformatted.patch