name: C/C++ CI

on:
  pull_request:
    branches: ["main", "ci/**"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build test
      run: make -s build
    - name: run test
      run: make -s test
    - name: upload test logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Test-Logs
        path: build/pkg/tests/Testing/Temporary/LastTest.log
    - name: Upload coverage reports to Codecov
      if: always()
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        gcov: true

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt install clang-format
      - name: Run clang-format
        run: |
          git ls-files | grep -E "\.(c|cpp|h|hpp|tpp)$" | xargs clang-format -i -style=file || true
      - name: Check for changes
        run: |
          if ! git diff --quiet ; then
            exit 1
          fi
